#!/bin/sh
input_directory=/bigdata-course/datasets/text
output_directory=$HOME/output-hadoop
rm -rvf $output_directory
hdfs dfs -rm -r  $HOME/output-hadoop
yarn jar build/wordcount.jar \
    -libjars /gfs/jars/lucene/6.2.0/lucene-core-6.2.0.jar,/gfs/jars/lucene/6.2.0/lucene-analyzers-common-6.2.0.jar \
    -files /gfs/jars/lucene/6.2.0/lucene-core-6.2.0.jar,/gfs/jars/lucene/6.2.0/lucene-analyzers-common-6.2.0.jar \
    $input_directory $output_directory
